{
 "title": "Adventure Game Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Forge Heat",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "forge_heat{location=\"blacksmith\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Forge Heat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "forge_heat{location=\"blacksmith\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swords",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "swords", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Holy Sword",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "holy_sword", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Evil Sword",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "evil_sword", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quest Log",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "{service_name=\"adventure\"} != `failed` | label_format level=detected_level"
    }
   ]
  }
 ]
}